[package]
name = "structfs-json-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "JSON-based store implementations for StructFS"

[dependencies]
structfs-core-store = { path = "../core-store" }
structfs-serde-store = { path = "../serde-store" }

serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
