[package]
name = "structfs-http"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "HTTP client and server stores for StructFS"

[features]
default = ["blocking"]
blocking = ["reqwest/blocking"]
async = ["tokio"]

[dependencies]
structfs-store = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
erased-serde = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
http = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
wiremock = { workspace = true }
tokio = { workspace = true }
