[package]
name = "structfs-http"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "HTTP client stores for StructFS"

[features]
default = ["blocking"]
blocking = ["reqwest/blocking"]

[dependencies]
structfs-core-store = { path = "../core-store" }
structfs-serde-store = { path = "../serde-store" }

serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
http = { workspace = true }
url = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }
tokio = { workspace = true }
