[package]
name = "featherweight"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Block-based pico-process runtime using WASM sandboxes"
