[package]
name = "structfs-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core store traits and types for StructFS"

[features]
test-utils = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
erased-serde = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
